# Generated by Django 4.1.7 on 2023-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='purchase_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
