# Generated by Django 4.1.7 on 2023-03-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_opinion_purchase_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrapper.product'),
            preserve_default=False,
        ),
    ]
