# Generated by Django 4.1.7 on 2023-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_opinion_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opinion',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
