# Generated by Django 4.1.7 on 2023-03-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_opinion_dislikes_opinion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='description',
            field=models.TextField(default='brak'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='recommended',
            field=models.BooleanField(null=True),
        ),
    ]
