# Generated by Django 4.1.7 on 2023-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_opinion_description_opinion_opinion_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cons',
        ),
        migrations.DeleteModel(
            name='Pros',
        ),
        migrations.AddField(
            model_name='opinion',
            name='cons',
            field=models.TextField(default='brak'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='pros',
            field=models.TextField(default='brak'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
