# Generated by Django 4.1.7 on 2023-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_delete_cons_delete_pros_opinion_cons_opinion_pros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='cons',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='pros',
            field=models.TextField(null=True),
        ),
    ]
